# Generated by Django 6.0.3 on 2026-03-31 16:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='specialization',
            field=models.CharField(choices=[('CS', 'Computer Science'), ('CY', 'Cyber Security'), ('SE', 'Software Engineering'), ('IT', 'Information Technology'), ('DS', 'Data Science')], default='CS', max_length=2),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
