# Generated by Django 6.0.3 on 2026-03-31 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_studentprofile_specialization_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='department',
            field=models.CharField(choices=[('Computer Science', 'Computer Science')], default='Computer Science', editable=False, max_length=100),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='level',
            field=models.IntegerField(choices=[(100, '100'), (200, '200'), (300, '300'), (400, '400'), (500, '500')], default=100),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='specialization',
            field=models.CharField(choices=[('AI', 'Artificial Intelligence'), ('ML', 'Machine Learning'), ('CG', 'Computer Graphics'), ('CY', 'Cyber Security'), ('SE', 'Software Engineering'), ('IT', 'Information Technology'), ('DS', 'Data Science'), ('CC', 'Cloud Computing')], max_length=2),
        ),
    ]
