# Generated by Django 6.0.3 on 2026-03-31 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_studentprofile_department_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='level',
            field=models.IntegerField(choices=[(100, '100'), (200, '200'), (300, '300'), (400, '400')], default=100),
        ),
    ]
