# Generated by Django 6.0.3 on 2026-04-24 16:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_course_enrollment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='credit_units',
            field=models.IntegerField(default=3, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(3)]),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='semester',
            field=models.CharField(choices=[('1st', '1st Semester'), ('2nd', '2nd Semester')], default='1st', max_length=3),
        ),
    ]
