# Generated by Django 6.0.3 on 2026-04-24 18:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_course_credit_units'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='credit_units',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3')], default=3, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(3)]),
        ),
    ]
