# Generated by Django 6.0.3 on 2026-05-07 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_course_credit_units'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='specialization',
            field=models.CharField(choices=[('AI', 'Artificial Intelligence'), ('ML', 'Machine Learning'), ('CG', 'Computer Graphics'), ('CY', 'Cyber Security'), ('SE', 'Software Engineering'), ('IT', 'Information Technology'), ('DS', 'Data Science'), ('CC', 'Cloud Computing'), ('CN', 'Computer Networking & Communications'), ('HC', 'Human-Computer Interaction')], max_length=2),
        ),
    ]
