# Generated by Django 6.0.3 on 2026-05-09 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_studentprofile_specialization'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollment',
            name='grade',
            field=models.CharField(blank=True, choices=[('IP', 'In Progress'), ('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('F', 'F')], default='IP', max_length=2),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='specialization',
            field=models.CharField(choices=[('AI', 'Artificial Intelligence'), ('ML', 'Machine Learning'), ('CG', 'Computer Graphics'), ('CY', 'Cyber Security'), ('SE', 'Software Engineering'), ('IT', 'Information Technology'), ('DS', 'Data Science'), ('CC', 'Cloud Computing')], max_length=2),
        ),
        migrations.AlterUniqueTogether(
            name='enrollment',
            unique_together={('student', 'course', 'semester')},
        ),
    ]
