# Generated by Django 6.0.3 on 2026-05-12 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_enrollment_grade_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='is_mandatory',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='specialization',
            field=models.CharField(choices=[('AI', 'Artificial Intelligence'), ('ML', 'Machine Learning'), ('CG', 'Computer Graphics'), ('CY', 'Cyber Security'), ('SE', 'Software Engineering'), ('IT', 'Information Technology'), ('DS', 'Data Science'), ('CC', 'Cloud Computing'), ('CN', 'Computer Networking & Communications'), ('HC', 'Human-Computer Interaction')], max_length=2),
        ),
        migrations.CreateModel(
            name='Prerequisite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_code', models.CharField(max_length=10)),
                ('required_course_code', models.CharField(max_length=10)),
                ('min_grade', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E')], default='E', max_length=1)),
            ],
            options={
                'unique_together': {('course_code', 'required_course_code')},
            },
        ),
    ]
