# Generated by Django 6.0.3 on 2026-05-12 21:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_course_is_mandatory_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='prerequisite',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='prerequisite',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='unlocks', to='core.course'),
        ),
        migrations.AddField(
            model_name='prerequisite',
            name='required_course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prerequisites', to='core.course'),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='grade',
            field=models.CharField(blank=True, choices=[('IP', 'In Progress'), ('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E'), ('F', 'F')], default='IP', max_length=2),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='specialization',
            field=models.CharField(choices=[('AI', 'Artificial Intelligence'), ('ML', 'Machine Learning'), ('CG', 'Computer Graphics'), ('CY', 'Cyber Security'), ('SE', 'Software Engineering'), ('IT', 'Information Technology'), ('DS', 'Data Science'), ('CC', 'Cloud Computing')], max_length=2),
        ),
        migrations.RemoveField(
            model_name='prerequisite',
            name='course_code',
        ),
        migrations.RemoveField(
            model_name='prerequisite',
            name='required_course_code',
        ),
    ]
