# Generated by Django 6.0.3 on 2026-05-12 21:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_prerequisite_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='prerequisite',
            unique_together={('course', 'required_course')},
        ),
    ]
